[package]
name = "hero_in_trouble"
version = "0.1.0"
edition = "2021"

authors = ["ilRECh ildar.rch@gmail.com"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.1"
